// <auto-generated />
namespace Conetados.Webapi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdicionandomodeloparapersistenciadeaceitesdeTermosdeUso : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionandomodeloparapersistenciadeaceitesdeTermosdeUso));
        
        string IMigrationMetadata.Id
        {
            get { return "201706091757463_Adicionando modelo para persistencia de aceites de Termos de Uso."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
